### ISSUE TITLE
Person

### ISSUE THREAD

**Issue by angadgadre** [alagappanr/orangehummer#4]
name: Robin Webb
--date of birth is of the type c. yyyy
--need to remove ref html tag
--website name, if empty contains {{URL markup

name: Gary North
--dateof birth is of the type february 1942
--Not a single occupation. So, should the schema have this as multivalued? (there are other examples of this too). And it is listed in order of importance in the markup.
--Have kept schema as multivalued for name, here this person is known by alternative names

name: kyra sedgwick
--spouse not parsed
-- [&lt;br /&gt]; line breaks not parsed

**Comment by vinothsdev** [comment]
Issue resolved in latest xml file.
