### ISSUE TITLE
Parsing : unwanted tag to be removed

### ISSUE THREAD

**Issue by techpalaniappanm** [alagappanr/orangehummer#6]
imagesize
alt
bgcolour
term
honorificsuffix
honorificprefix
hometown
signature
wrestling weight
abbr
hangul
module
mr
rrborn
hangulborn
color
rr
mrborn
child
size
embed
filename
description
work
accessdate
date
agent
origin
eye color
hair color
natural bust
df
issue
m
othernameslang
precision
criminalstatus
criminalpenalty
criminalcharge
publisher
image size
dead
age
alive

will add once, I find more

**Comment by vinothsdev** [comment]
Issue fixed.

**Comment by techpalaniappanm** [comment]
Getting tags honorificsuffix and honorificprefix

**Comment by vinothsdev** [comment]
fixed.
