### ISSUE TITLE
type having mutli values

### ISSUE THREAD

**Issue by techpalaniappanm** [alagappanr/orangehummer#9]
id">1929619</field>
type">person</field>
occupation">Continuity announcer and newsreader</field>
module">{{Listen</field>
birthdate">1961-01-01T00:00:00Z</field>
employer">BBC</field>
education">Stratford-upon-Avon Grammar School for Girls</field>
type">speech</field>
birthplace">Oxford ,  England</field>
embed">yes</field>
education">Goldsmiths, University of London</field>
title">Corrie Corfield's voice</field>
description">recorded November 2012 }}</field>
name">Corrie Kear Ware Corfield</field>
filename">Corrie Corfield voice.ogg</field>

**Comment by vinothsdev** [comment]
Issue fixed along with Issue #6
